-- Run before deploying the resident/access model. Stop API and worker processes first.
-- Review classification: organization administrators and existing team owners/members retain login accounts.
-- All other legacy users become residents and their login accounts are soft-deleted.
-- Assigned privileged users also get separate resident records to preserve assignment history.
BEGIN;
LOCK TABLE users, locations, user_locations, dev_teams, dev_team_members IN ACCESS EXCLUSIVE MODE;
ALTER TABLE users ADD COLUMN account_type varchar(20) NOT NULL DEFAULT 'DEVELOPER'
    CHECK (account_type IN ('ADMINISTRATOR', 'DEVELOPER'));
UPDATE users u SET account_type = 'ADMINISTRATOR' WHERE EXISTS
    (SELECT 1 FROM organizations o WHERE o.admin_user_id = u.user_id);
-- Existing membership is preserved: an administrator who is also a developer retains that category.
UPDATE users u SET account_type = 'DEVELOPER' WHERE EXISTS
    (SELECT 1 FROM dev_team_members m WHERE m.user_id = u.user_id) OR EXISTS
    (SELECT 1 FROM dev_teams t WHERE t.owner_user_id = u.user_id);
ALTER TABLE locations ALTER COLUMN location_type TYPE varchar(20) USING 'OPERATIONAL'::varchar(20);
ALTER TABLE locations ALTER COLUMN location_type SET DEFAULT 'OPERATIONAL';
ALTER TABLE locations ALTER COLUMN location_type SET NOT NULL;
ALTER TABLE locations ADD CHECK (location_type IN ('OPERATIONAL', 'TESTING'));
ALTER TABLE lambda_alerts ADD COLUMN testing boolean NOT NULL DEFAULT false;
ALTER TABLE devices ADD COLUMN testing boolean NOT NULL DEFAULT false;
CREATE TABLE residents (
    resident_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id int NOT NULL REFERENCES organizations(organization_id),
    first_name varchar(250), last_name varchar(250), email varchar(250), phone varchar(50),
    synthetic boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL, deleted_at timestamp
);
CREATE INDEX i_residents_organization ON residents(organization_id);
CREATE TABLE resident_locations (
    resident_id int NOT NULL REFERENCES residents(resident_id),
    location_id int NOT NULL REFERENCES locations(location_id),
    start_date timestamp NOT NULL, end_date timestamp,
    PRIMARY KEY (resident_id, location_id, start_date)
);
CREATE INDEX i_resident_locations_location ON resident_locations(location_id);

INSERT INTO residents (resident_id, organization_id, first_name, last_name, email, phone, created_at, deleted_at)
SELECT u.user_id, u.organization_id, u.first_name, u.last_name, u.email, u.phone, u.created_at, u.deleted_at
FROM users u
WHERE EXISTS (SELECT 1 FROM user_locations ul WHERE ul.user_id = u.user_id)
   OR (NOT EXISTS (SELECT 1 FROM organizations o WHERE o.admin_user_id = u.user_id)
       AND NOT EXISTS (SELECT 1 FROM dev_team_members m WHERE m.user_id = u.user_id)
       AND NOT EXISTS (SELECT 1 FROM dev_teams t WHERE t.owner_user_id = u.user_id));
SELECT setval(pg_get_serial_sequence('residents', 'resident_id'), COALESCE(MAX(resident_id), 1), MAX(resident_id) IS NOT NULL) FROM residents;
INSERT INTO resident_locations SELECT user_id, location_id, start_date, end_date FROM user_locations;
UPDATE users u SET deleted_at = COALESCE(deleted_at, NOW()), password = NULL
WHERE NOT EXISTS (SELECT 1 FROM organizations o WHERE o.admin_user_id = u.user_id)
  AND NOT EXISTS (SELECT 1 FROM dev_team_members m WHERE m.user_id = u.user_id)
  AND NOT EXISTS (SELECT 1 FROM dev_teams t WHERE t.owner_user_id = u.user_id);
DROP VIEW IF EXISTS v_reports_organization_users;
DROP TABLE user_locations;
ALTER TABLE dev_teams ADD COLUMN organization_id int REFERENCES organizations(organization_id);
UPDATE dev_teams t SET organization_id = u.organization_id FROM users u WHERE u.user_id = t.owner_user_id;
ALTER TABLE dev_teams ALTER COLUMN organization_id SET NOT NULL;
-- Fail rather than silently move developers between organizations.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM dev_team_members m JOIN dev_teams t USING (dev_team_id)
        JOIN users u USING (user_id) WHERE u.organization_id IS DISTINCT FROM t.organization_id) THEN
        RAISE EXCEPTION 'Resolve cross-organization team membership before migration';
    END IF;
END $$;
ALTER TABLE dev_teams ADD COLUMN testing_location_id int UNIQUE REFERENCES locations(location_id);
DO $$ DECLARE team record; test_location int; BEGIN
    FOR team IN SELECT * FROM dev_teams LOOP
        INSERT INTO locations (location_name, organization_id, location_type, created_at, timezone)
        VALUES (team.name || ' testing', team.organization_id, 'TESTING', NOW(), 'UTC') RETURNING location_id INTO test_location;
        UPDATE dev_teams SET testing_location_id = test_location WHERE dev_team_id = team.dev_team_id;
        INSERT INTO dev_team_members (dev_team_id, user_id, start_date) VALUES (team.dev_team_id, team.owner_user_id, NOW())
            ON CONFLICT (dev_team_id, user_id) DO UPDATE SET end_date = NULL, start_date = NOW();
    END LOOP;
END $$;
ALTER TABLE dev_teams ALTER COLUMN testing_location_id SET NOT NULL;
ALTER TABLE dev_teams DROP CONSTRAINT uk_lambda_developer_team_name;
ALTER TABLE dev_teams ADD CONSTRAINT uk_lambda_developer_team_name UNIQUE (organization_id, name);
CREATE TABLE dev_team_locations (
    dev_team_id int NOT NULL REFERENCES dev_teams(dev_team_id) ON DELETE CASCADE,
    location_id int NOT NULL REFERENCES locations(location_id),
    PRIMARY KEY (dev_team_id, location_id)
);
INSERT INTO dev_team_locations SELECT dev_team_id, testing_location_id FROM dev_teams;
-- Existing test assignments cannot keep running against operational data. Recreate them on test locations.
UPDATE lambda_assignments SET end_date = NOW() WHERE is_testing AND deleted_at IS NULL;

CREATE OR REPLACE VIEW v_reports_locations
AS
SELECT l.location_id,
       l.location_name,
       l.created_at,
       l.organization_id,
       l.addr_street1,
       l.addr_street2,
       l.city,
       l.postal_code,
       l.state,
       l.country_code,
       o.organization_name
FROM locations l
         JOIN organizations o ON o.organization_id = l.organization_id AND o.deleted_at IS NULL
WHERE l.deleted_at IS NULL AND l.location_type = 'OPERATIONAL';

CREATE OR REPLACE VIEW v_reports_devices
AS
SELECT d.device_uuid,
       d.device_name,
       d.model,
       d.type_id,
       dt.name AS device_type,
       ld.location_id
FROM devices d
         JOIN device_types dt ON dt.type_id = d.type_id
         JOIN location_devices ld ON ld.device_uuid = d.device_uuid
            AND ld.start_date <= NOW() AND (ld.end_date IS NULL OR ld.end_date > NOW());

CREATE OR REPLACE VIEW v_reports_organization_residents
AS
SELECT u.resident_id,
       u.created_at,
       u.first_name,
       u.last_name,
       u.email,
       u.phone,
       l.organization_id,
       l.location_id,
       l.addr_street1,
       l.addr_street2,
       l.city,
       l.postal_code,
       l.state,
       l.country_code
FROM locations l
         JOIN resident_locations ul ON ul.location_id = l.location_id
            AND ul.start_date <= NOW() AND (ul.end_date IS NULL OR ul.end_date > NOW())
         JOIN residents u ON u.resident_id = ul.resident_id AND u.deleted_at IS NULL
WHERE l.deleted_at IS NULL AND l.location_type = 'OPERATIONAL';

COMMIT;
