# See https://docs.spring.io/spring-boot/appendix/application-properties/index.htm

# Location of the logging configuration file
logging.config=classpath:logback.xml
# Application context
spring.main.allow-bean-definition-overriding=true
#spring.main.allow-circular-references=true

# Server HTTP port
server.port=8082

# See https://docs.spring.io/spring-boot/reference/actuator/endpoints.html for available management endpoints
# Network address to which the management endpoints should bind
management.server.address=127.0.0.1
# Management endpoint HTTP port (uses the same port as the application by default)
management.server.port=8083
# Whether to enable or disable all endpoints by default
management.endpoints.access.default=none
# Whether to enable the shutdown endpoint
# Shutdown: POST http://localhost:8083/man/shutdown
management.endpoint.shutdown.access=unrestricted
# Lambda workload: GET http://localhost:8083/man/lambdaworkload
management.endpoint.lambdaworkload.access=read-only
# Base path for Web management endpoints
management.endpoints.web.base-path=/man
# Endpoint IDs that should be included
management.endpoints.web.exposure.include=shutdown,lambdaworkload
management.cloudfoundry.enabled=false
