# See https://docs.spring.io/spring-boot/appendix/application-properties/index.html

# Location of the logging configuration file
logging.config=classpath:logback.xml
# Application context
spring.main.allow-bean-definition-overriding=true
spring.threads.virtual.enabled=true

# Server HTTP port
server.port=8086

# Lambda workload: GET http://localhost:8087/man/lambdaworkload
management.server.address=127.0.0.1
management.server.port=8087
management.endpoints.access.default=none
management.endpoint.lambdaworkload.access=read-only
management.endpoints.web.base-path=/man
management.endpoints.web.exposure.include=lambdaworkload
management.cloudfoundry.enabled=false

# https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.spring-mvc.customize-jackson-objectmapper
spring.jackson.default-property-inclusion=non_null
spring.jackson.visibility.creator=none
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=false
spring.jackson.deserialization.FAIL_ON_NULL_FOR_PRIMITIVES=false
spring.jackson.mapper.SORT_PROPERTIES_ALPHABETICALLY=false

# Tomcat
server.tomcat.accept-count=200
server.tomcat.max-connections=10000
server.tomcat.connection-timeout=60000
server.tomcat.processor-cache=2000
