package dev.olegz.vf.worker.service;

import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.Base64;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;

import dev.olegz.vf.aws.client.AwsClients;
import dev.olegz.vf.aws.error.AwsExceptions;
import dev.olegz.vf.common.objectmap.StringMapper;
import dev.olegz.vf.common.props.PropertyStore;
import dev.olegz.vf.worker.domain.LambdaOutput;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import software.amazon.awssdk.core.SdkBytes;
import software.amazon.awssdk.core.exception.SdkClientException;
import software.amazon.awssdk.http.apache.ApacheHttpClient;
import software.amazon.awssdk.retries.DefaultRetryStrategy;
import software.amazon.awssdk.services.lambda.LambdaClient;
import software.amazon.awssdk.services.lambda.model.*;


@Service("lambdaFunctionInvoker")
public class LambdaFunctionInvoker {
    private static final Logger logger = LoggerFactory.getLogger(LambdaFunctionInvoker.class);

    private static final SystemLogLevel SYS_LOG_LEVEL = SystemLogLevel.INFO;
    private static final ApplicationLogLevel lambda_LOG_LEVEL = ApplicationLogLevel.WARN;

    private static LoggingConfig getLoggingConfig() {
        String logLevel = PropertyStore.getString("vf.lambda.systemLogLevel", SYS_LOG_LEVEL.name());
        SystemLogLevel sysLogLevel = SystemLogLevel.fromValue(logLevel.toUpperCase());
        if (sysLogLevel == null) {
            logger.warn("Wrong system log level '" + logLevel + "', defaulting to " + SYS_LOG_LEVEL);
            sysLogLevel = SYS_LOG_LEVEL;
        }

        logLevel = PropertyStore.getString("vf.lambda.applicationLogLevel", lambda_LOG_LEVEL.name());
        ApplicationLogLevel appLogLevel = ApplicationLogLevel.fromValue(logLevel.toUpperCase());
        if (appLogLevel == null) {
            logger.warn("Wrong application log level '" + logLevel + "', defaulting to " + lambda_LOG_LEVEL);
            appLogLevel = lambda_LOG_LEVEL;
        }

        return LoggingConfig.builder()
            .logFormat(LogFormat.JSON)
            .systemLogLevel(sysLogLevel)
            .applicationLogLevel(appLogLevel)
            .build();
    }

    private static final Class<?>[] noRetryApiExceptions = {
        InvalidParameterValueException.class,
        InvalidRequestContentException.class,
        CodeStorageExceededException.class,
        TooManyRequestsException.class,
        RequestTooLargeException.class,
        ResourceConflictException.class,
        ResourceNotFoundException.class,
        LambdaException.class,
        software.amazon.awssdk.services.iam.model.NoSuchEntityException.class
    };

    private static boolean isRetryableApiException(Throwable e) {
        for (var cls : noRetryApiExceptions) {
            if (cls.isInstance(e)) return false;
        }
        return true;
    }

    private void makeInvokeClient() {
        Duration maxTimeout = Duration.ofSeconds(900);
        clientCache.set(AwsClients.lambdaClient(
            builder -> builder
                .httpClient(
                    ApacheHttpClient.builder()
                        .maxConnections(PropertyStore.getInt("vf.aws.s3.client.maxConnections", 500))
                        .connectionTimeout(Duration.ofMillis(PropertyStore.getLong("vf.aws.s3.client.connectionTimeout", 5000L)))
                        .socketTimeout(maxTimeout)
                        .build()
                ).overrideConfiguration(
                    conf -> conf.apiCallAttemptTimeout(maxTimeout)
                        .apiCallTimeout(maxTimeout)
                        .retryStrategy(DefaultRetryStrategy.doNotRetry())
                )
        ));
    }

    private LambdaClient makeAsyncInvokeClient() {
        return AwsClients.lambdaClient();
    }

    private final AtomicReference<LambdaClient> clientCache = new AtomicReference<>(null);

    public LambdaFunctionInvoker() {
    }

    @PostConstruct
    public void awsLambdaInit() {
        makeInvokeClient();
    }

    private void reconnect(LambdaClient oldClient) {
        LambdaClient client = clientCache.get();
        if (client == oldClient) {
            makeInvokeClient();
            oldClient.close();
        }
    }

    public void destroy() {
        LambdaClient client = clientCache.getAndSet(null);
        if (client != null) client.close();
    }

    /**
     * Invoke specified function in the request-response mode.
     * Note:
     * This method throws an exception only if a retry is required.
     * Otherwise, the error message is stored in the output object.
     * @return output generated by the lambda code or by Lambda engine in case of unhandled function error
     */
    LambdaOutput invoke(String functionName, String input) {
        LambdaClient client = clientCache.get();

        long startTime = System.currentTimeMillis();

        InvokeResponse response;
        try {
            response = client.invoke(
                bld -> bld.functionName(functionName)
                    .payload(SdkBytes.fromUtf8String(input))
                    .invocationType(InvocationType.REQUEST_RESPONSE)
                    .logType(LogType.TAIL)
            );
        } catch (Exception e) {
            if (e instanceof SdkClientException) {
                reconnect(client);
            }
            throw e;
        }

        LambdaOutput lambdaOutput;

        if (response.payload() == null) {
            lambdaOutput = new LambdaOutput();
            lambdaOutput.errorMessage = "Empty response body";
        } else {
            String payload = response.payload().asUtf8String();
            try {
                lambdaOutput = StringMapper.readValue(payload, LambdaOutput.class);
                if ((lambdaOutput.errorMessage != null) && (response.logResult() != null)) {
                    try {
                        String logResult = new String(Base64.getDecoder().decode(response.logResult()), StandardCharsets.UTF_8);
                        lambdaOutput.errorMessage = lambdaOutput.errorMessage + "\nLog:\n" + logResult;
                    } catch (Exception e) {
                        logger.warn("Cannot parse log result: " + response.logResult());
                    }
                }
            } catch (Exception e) {
                lambdaOutput = new LambdaOutput();
                lambdaOutput.errorMessage = "Cannot parse lambda output: " + payload;
            }
        }

        if (lambdaOutput.startTime == 0L) lambdaOutput.startTime = startTime;
        if (lambdaOutput.endTime == 0L) lambdaOutput.endTime = System.currentTimeMillis();
        return lambdaOutput;
    }

    /**
     * Invoke specified function asynchronously in the event-driven mode.
     * @return AWS requestId
     */
    String invokeAsync(String functionName, String input) {
        if (logger.isDebugEnabled()) {
            logger.debug(">invokeAsync() functionName=" + functionName + ", input=" + input);
        }

        String awsRequestId;
        try (LambdaClient client = makeAsyncInvokeClient()) {
            InvokeResponse invokeResponse = client.invoke(
                r -> r.functionName(functionName)
                    .invocationType(InvocationType.EVENT)
                    .payload(SdkBytes.fromString(input, StandardCharsets.UTF_8))
            );
            awsRequestId = getAwsRequestId(invokeResponse);

        } catch (Exception e) {
            throw AwsExceptions.wrapAwsException(e, "Exception while invoking async functionName=" + functionName);
        }
        logger.debug("<invokeAsync()");
        return awsRequestId;
    }


    private static String getAwsRequestId(InvokeResponse response) {
        List<String> awsRequestIds = response.sdkHttpResponse().headers().get("x-amzn-RequestId");
        return (awsRequestIds == null) || awsRequestIds.isEmpty() ? null : awsRequestIds.getFirst();
    }

}
