/*==============================================================*/
/* Vigilo Framework schema for PostgreSQL */
/*                                                              */
/* Prerequisites (run first, as a superuser):                   */
/*   \i postgresql/config/create_database.sql   -- CREATE DATABASE vf (UTF8) */
/* Then connect to it before running this script:               */
/*   \c vf                                                   */
/*                                                              */
/* READ COMMITTED is the PostgreSQL default and is also pinned  */
/* in postgresql/config/postgresql.conf, so no isolation set is */
/* needed here.                                                 */
/*                                                              */
/* Identity columns use GENERATED BY DEFAULT so controlled seed */
/* and migration scripts can insert explicit identifiers.      */
/*==============================================================*/

\c vf

/*==============================================================*/
/* Tables                                                       */
/*==============================================================*/

CREATE TABLE organizations
(
   organization_id      int GENERATED BY DEFAULT AS IDENTITY,
   organization_name    varchar(250),
   parent_id            int,
   admin_user_id        int,
   created_at           timestamp NOT NULL,
   deleted_at           timestamp,
   addr_street1         varchar(250),
   addr_street2         varchar(250),
   city                 varchar(250),
   state                varchar(50),
   country_code         varchar(3),
   postal_code          varchar(250),
   timezone             varchar(50),
   PRIMARY KEY (organization_id)
);


CREATE TABLE organizations_hierarchy
(
   parent_organization_id   int not null,
   child_organization_id    int not null,
   level                    smallint not null,
   PRIMARY KEY (child_organization_id, parent_organization_id)
);

CREATE INDEX i_organizations_hierarchy_parent ON organizations_hierarchy (parent_organization_id);

CREATE TABLE locations (
  location_id       int GENERATED BY DEFAULT AS IDENTITY,
  location_name     varchar(250),
  created_at     timestamp NOT NULL,
  deleted_at        timestamp,
  organization_id   int,
  timezone          varchar(250),
  location_type     smallint,
  addr_street1      varchar(250),
  addr_street2      varchar(250),
  city              varchar(100),
  state             varchar(50),
  country_code      varchar(3),
  postal_code       varchar(50),
  PRIMARY KEY (location_id),
  CONSTRAINT fk_locations_organization
  FOREIGN KEY (organization_id)
  REFERENCES organizations (organization_id)
  ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX i_locations_organization ON locations (organization_id);

CREATE TABLE users
(
    user_id             int GENERATED BY DEFAULT AS IDENTITY,
    username            varchar(250),
    password            varchar(250),
    created_at          timestamp not null,
    deleted_at          timestamp,
    first_name          varchar(250),
    last_name           varchar(250),
    email               varchar(250),
    phone               varchar(50),
    organization_id     int,
    PRIMARY KEY (user_id)
);

CREATE TABLE user_locations
(
  user_id               int not null,
  location_id           int not null,
  start_date            timestamp not null,
  end_date              timestamp,
  PRIMARY KEY (user_id, location_id, start_date)
);

CREATE INDEX i_user_locations_location ON user_locations (location_id);
CREATE INDEX i_users_username ON users (username);

CREATE TABLE device_types
(
  type_id               int not null,
  name                  varchar(250) not null,
  PRIMARY KEY (type_id),
  CONSTRAINT uk_device_types_name UNIQUE (name)
);

CREATE TABLE devices
(
  device_uuid           varchar(250) not null,
  organization_id       int not null,
  type_id               int not null,
  device_name           varchar(250),
  serial_number         varchar(250),
  model                 varchar(250),
  vendor                varchar(250),
  manufacturer          varchar(250),
  PRIMARY KEY (device_uuid),
  CONSTRAINT fk_devices_organization
  FOREIGN KEY (organization_id)
  REFERENCES organizations (organization_id)
  ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_devices_type
  FOREIGN KEY (type_id)
  REFERENCES device_types (type_id)
  ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX i_devices_organization_type ON devices (organization_id, type_id);

CREATE TABLE device_current_states
(
  device_uuid           varchar(250) not null,
  current_state         jsonb not null,
  measured_at           timestamp(3) not null,
  received_at           timestamp(3) not null,
  PRIMARY KEY (device_uuid),
  CONSTRAINT fk_device_current_states_device
  FOREIGN KEY (device_uuid)
  REFERENCES devices (device_uuid)
  ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE location_current_states
(
  location_id           int not null,
  current_state         varchar(50) not null,
  state_date            timestamp(3) not null,
  PRIMARY KEY (location_id),
  CONSTRAINT fk_location_current_states_location
  FOREIGN KEY (location_id)
  REFERENCES locations (location_id)
  ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE location_devices
(
  device_uuid           varchar(250) not null,
  location_id           int not null,
  start_date            timestamp not null,
  end_date              timestamp,
  PRIMARY KEY (device_uuid, location_id, start_date),
  CONSTRAINT fk_location_devices_device
  FOREIGN KEY (device_uuid)
  REFERENCES devices (device_uuid)
  ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_location_devices_location
  FOREIGN KEY (location_id)
  REFERENCES locations (location_id)
  ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX i_location_devices_location ON location_devices (location_id);


CREATE TABLE dev_teams
(
    dev_team_id         int GENERATED BY DEFAULT AS IDENTITY,
    owner_user_id       int not null,
    name                varchar(100) not null,
    description         varchar(1000),
    PRIMARY KEY (dev_team_id),
    CONSTRAINT uk_lambda_developer_team_name UNIQUE (name)
);

CREATE TABLE dev_team_members
(
    dev_team_id         int not null,
    user_id             int not null,
    start_date timestamp not null,
    end_date timestamp,
    PRIMARY KEY (dev_team_id, user_id)
);

CREATE INDEX i_dev_team_members_user ON dev_team_members (user_id);

CREATE TABLE lambdas
(
    lambda_id              int GENERATED BY DEFAULT AS IDENTITY,
    name                varchar(250) not null,
    description         varchar(1000),
    metadata            jsonb,
    dev_team_id         int not null default 0,
    code_upload_id      int,
    created_at       timestamp not null,
    max_version         varchar(50),
    max_sequence        int not null default 0,
    PRIMARY KEY (lambda_id),
    CONSTRAINT uk_lambdas_name UNIQUE (name)
);

CREATE INDEX i_lambdas_dev_team ON lambdas (dev_team_id);

CREATE TABLE lambda_code_uploads
(
    upload_id               int GENERATED BY DEFAULT AS IDENTITY,
    status                  varchar(30) not null,
    status_date             timestamp not null,
    message                 varchar(10000),
    lambda_version_id          int not null,
    code_object_id          varchar(250),
    arch                    smallint,
    memory                  int,
    timeout                 int,
    lambda_id                  int not null,
    user_id                 int,
    function_name           varchar(250),
    async_function_name        varchar(250),
    function_deletion_date  timestamp,
    function_deletion_info  varchar(1000),
    repo_name               varchar(250),
    stage_image             varchar(150),
    base_image              varchar(150),
    PRIMARY KEY (upload_id)
);


CREATE TABLE lambda_daily_metrics
(
    lambda_version_id            int      not null,
    start_date                timestamp not null,
    lambda_id                    int      not null,
    lane                      varchar(30) not null,
    invocations               int,
    throttles                 int,
    errors                    int,
    total_duration            bigint,
    gb_s_billed               bigint,
    avg_concurrent_executions int,
    max_concurrent_executions int,
    async_events_received     int,
    async_events_dropped      int,
    async_event_age           int,
    max_async_event_age       int,
    dead_letter_errors        int
);

CREATE INDEX i_lambda_daily_metrics_app ON lambda_daily_metrics (lambda_id, start_date);


CREATE TABLE lambda_versions
(
    lambda_version_id      int GENERATED BY DEFAULT AS IDENTITY,
    lambda_id              int not null,
    created_at       timestamp not null,
    status              varchar(30),
    status_date         timestamp,
    arch                smallint,
    code_upload_id      int,
    lambda_trigger         int not null,
    lambda_version         varchar(50) not null,
    sequence_number     int not null,
    schedule            jsonb,
    whatsnew            text,
    created_by          int,
    PRIMARY KEY(lambda_version_id),
    CONSTRAINT uk_lambda_versions_sequence UNIQUE (lambda_id, sequence_number)
);

CREATE INDEX i_lambda_versions_lambda_status ON lambda_versions (lambda_id, status);


CREATE TABLE lambda_active_versions
(
    lambda_id                  int not null,
    is_public               boolean not null,
    latest_status           smallint not null,
    lambda_trigger             int not null,
    timeout                 smallint not null,
    memory                  smallint not null,
    schedule                jsonb,
    schedule_start_date     timestamp,
    code_object_id          varchar(250),
    function_name           varchar(250),
    async_function_name        varchar(250),
    function_start_date     timestamp(3),
    lambda_version_id          int unique,
    lambda_version             varchar(50),
    PRIMARY KEY(lambda_id, is_public)
);

ALTER TABLE lambda_active_versions
    ADD CONSTRAINT uk_lambda_active_versions_latest_status
        UNIQUE (lambda_id, latest_status);

ALTER TABLE lambda_active_versions
    ADD CONSTRAINT chk_public_latest_status
        CHECK ((is_public AND latest_status IN (0, 1)) OR
               (NOT is_public AND latest_status IN (1, 2)));


CREATE TABLE lambda_errors
(
    lambda_version_id      int not null,
    code_upload_date    timestamp(3) not null,
    error_signature     int not null,
    error_text          varchar(16000),
    error_message       varchar(150),
    error_count         int,
    error_date          timestamp,
    PRIMARY KEY (lambda_version_id, error_signature, code_upload_date)
);


CREATE TABLE lambda_alerts
(
    alert_id            uuid not null,
    idempotency_key     varchar(250) not null,
    payload_hash        varchar(64) not null,
    organization_id     int not null,
    location_id         int not null,
    device_uuid         varchar(250),
    alert_type          varchar(50) not null,
    severity            varchar(20) not null,
    status              varchar(20) not null,
    rule_id             varchar(100) not null,
    occurred_at         timestamp(3) not null,
    created_at          timestamp(3) not null,
    lambda_assignment_id   int not null,
    lambda_id              int not null,
    lambda_version_id      int not null,
    run_id              bigint not null,
    event_key           varchar(100) not null,
    changes_json        jsonb not null,
    acknowledged_at     timestamp(3),
    acknowledged_by     int,
    resolved_at         timestamp(3),
    resolved_by         int,
    PRIMARY KEY (alert_id)
);

CREATE UNIQUE INDEX ui_lambda_alerts_idempotency ON lambda_alerts (idempotency_key);
CREATE INDEX i_lambda_alerts_location_status ON lambda_alerts (location_id, status, occurred_at);
CREATE INDEX i_lambda_alerts_device ON lambda_alerts (device_uuid, occurred_at);


/*--------------------------------------------------------------*/
/* Partitioned by LIST(part), 8 partitions p0..p7               */
/*--------------------------------------------------------------*/
CREATE TABLE lambda_run_results
(
    part                smallint not null,
    result_code         smallint not null,
    lambda_assignment_id     int not null,
    lambda_version_id      int not null,
    request_date        timestamp(3) not null,
    processing_time     int not null,
    execution_time      int not null,
    memory              int not null,
    events_count        int not null,
    triggers            int not null,
    function_name       varchar(250),
    event_date          timestamp(3),
    server              varchar(3),
    retries             int,
    lane                varchar(30) not null,
    result_message      bytea
)
PARTITION BY LIST (part);

CREATE TABLE lambda_run_results_p0 PARTITION OF lambda_run_results FOR VALUES IN (0);
CREATE TABLE lambda_run_results_p1 PARTITION OF lambda_run_results FOR VALUES IN (1);
CREATE TABLE lambda_run_results_p2 PARTITION OF lambda_run_results FOR VALUES IN (2);
CREATE TABLE lambda_run_results_p3 PARTITION OF lambda_run_results FOR VALUES IN (3);
CREATE TABLE lambda_run_results_p4 PARTITION OF lambda_run_results FOR VALUES IN (4);
CREATE TABLE lambda_run_results_p5 PARTITION OF lambda_run_results FOR VALUES IN (5);
CREATE TABLE lambda_run_results_p6 PARTITION OF lambda_run_results FOR VALUES IN (6);
CREATE TABLE lambda_run_results_p7 PARTITION OF lambda_run_results FOR VALUES IN (7);

CREATE INDEX i_lambda_run_results_assignment ON lambda_run_results (lambda_assignment_id, request_date);
CREATE INDEX i_lambda_run_results_version ON lambda_run_results (lambda_version_id, request_date);


CREATE TABLE lambda_run_stat_day
(
    request_date        timestamp not null,
    lambda_version_id      int not null,
    result_code         smallint not null,
    request_count       int not null,
    assignment_count      int not null,
    execution_time      int not null,
    min_execution_time  int not null,
    max_execution_time  int not null,
    memory_volume       bigint,
    max_memory_used     int,
    lane                varchar(30) not null,
    gb_s_billed         int
);

CREATE INDEX i_lambda_run_stat_day_version ON lambda_run_stat_day (lambda_version_id);


CREATE TABLE lambda_assignments
(
   lambda_assignment_id    int GENERATED BY DEFAULT AS IDENTITY,
   lambda_id               int not null,
   is_testing           boolean not null,
   assignment_date      timestamp not null,
   user_id              int,
   location_id          int not null,
   end_date             timestamp,
   deleted_at           timestamp,
   private_variable_generation bigint not null default 0,
   schedule_last_date   timestamp,
   schedule_next_date   timestamp,
   PRIMARY KEY (lambda_assignment_id)
);

CREATE INDEX i_lambda_assignments_location ON lambda_assignments (location_id);
CREATE INDEX i_lambda_assignments_app ON lambda_assignments (lambda_id);


CREATE TABLE lambda_assignment_cleanup_queue
(
    lambda_assignment_id   int not null,
    cleanup_after       timestamp(3) not null,
    PRIMARY KEY (lambda_assignment_id)
);

CREATE INDEX i_lambda_assignment_cleanup_due ON lambda_assignment_cleanup_queue (cleanup_after, lambda_assignment_id);


CREATE TABLE cron_job_locks
(
    job_name            varchar(250) not null,
    owner_id            uuid not null,
    lock_until          timestamp(3) not null,
    PRIMARY KEY (job_name)
);


CREATE TABLE lambda_invoke_retry_outbox
(
    lambda_assignment_id   int not null,
    lane                varchar(30) not null,
    run_id              bigint not null,
    invocation_gen      smallint not null,
    payload             bytea not null,
    retry_at            timestamp(3) not null,
    claim_id            uuid,
    claim_until         timestamp(3),
    PRIMARY KEY (lambda_assignment_id, lane, run_id, invocation_gen)
);

CREATE INDEX i_lambda_invoke_retry_outbox_due
    ON lambda_invoke_retry_outbox (retry_at, claim_until, lambda_assignment_id);


CREATE TABLE lambda_async_submission_outbox
(
    lambda_assignment_id   int not null,
    run_id              bigint not null,
    payload             bytea not null,
    retry_at            timestamp(3) not null,
    attempt_count       int not null default 0,
    last_error          text,
    claim_id            uuid,
    claim_until         timestamp(3),
    PRIMARY KEY (lambda_assignment_id, run_id)
);

CREATE INDEX i_lambda_async_submission_outbox_due
    ON lambda_async_submission_outbox (retry_at, claim_until, lambda_assignment_id);


CREATE TABLE lambda_run_completion_outbox
(
    lambda_assignment_id   int not null,
    lane                varchar(30) not null,
    run_id              bigint not null,
    created_at          timestamp(3) not null,
    claim_id            uuid,
    claim_until         timestamp(3),
    PRIMARY KEY (lambda_assignment_id, lane, run_id)
);

CREATE INDEX i_lambda_run_completion_outbox_available
    ON lambda_run_completion_outbox (claim_until, created_at, lambda_assignment_id);


CREATE TABLE lambda_reset_outbox
(
    id                  bigint generated by default as identity,
    location_id         int not null,
    event_id            uuid not null,
    event_time          bigint not null,
    lambda_assignment_id   int not null,
    variable_generation bigint not null,
    created_at          timestamp(3) not null,
    claim_id            uuid,
    claim_until         timestamp(3),
    PRIMARY KEY (id)
);

CREATE INDEX i_lambda_reset_outbox_available
    ON lambda_reset_outbox (claim_until, id);


CREATE TABLE lambda_event_receipts
(
    event_id            varchar(64) not null,
    lambda_assignment_id   int not null,
    status              varchar(12) not null,
    run_id              bigint,
    created_at          timestamp(3) not null,
    completed_at        timestamp(3),
    PRIMARY KEY (event_id, lambda_assignment_id)
);

CREATE INDEX i_lambda_event_receipts_cleanup
    ON lambda_event_receipts (lambda_assignment_id, completed_at, created_at, event_id);


CREATE TABLE cache_invalidation_outbox
(
    id            bigint generated by default as identity,
    payload       bytea not null,
    created_at    timestamp(3) not null,
    claim_id      uuid,
    claim_until   timestamp(3),
    PRIMARY KEY (id)
);

CREATE INDEX i_cache_invalidation_outbox_claim
    ON cache_invalidation_outbox (claim_until, id);


CREATE TABLE lambda_latest_runs
(
    lambda_assignment_id     int not null,
    invocation_lane     varchar(30) not null,
    lambda_version_id      int not null,
    function_name       varchar(65) not null,
    pending_count       int not null,
    next_input_number     bigint,
    trigger_count       int not null,
    invocation_gen      smallint not null,
    is_started          boolean not null,
    run_id        bigint,
    prev_run_id   bigint,
    triggered_at       timestamp(3),
    expiry_date         timestamp(3),
    aws_request_id      varchar(50),
    aws_log_stream      varchar(100),
    aws_log_end_date    timestamp,
    PRIMARY KEY (lambda_assignment_id, invocation_lane)
);

CREATE INDEX i_lambda_latest_runs_aws_request_id ON lambda_latest_runs(aws_request_id);
CREATE INDEX i_lambda_latest_runs_expiry ON lambda_latest_runs(invocation_lane, expiry_date);


/*--------------------------------------------------------------*/
/* Partitioned by LIST(part), 4 partitions p0..p3              */
/*--------------------------------------------------------------*/
CREATE TABLE lambda_pending_inputs_p
(
    part                smallint not null,
    lambda_assignment_id     int     not null,
    lane                varchar(30) not null,
    input_number        bigint  not null,
    is_large_input      boolean not null,
    input_size          int     not null,
    input_data          bytea,
    large_input_data    bytea
)
PARTITION BY LIST (part);

CREATE TABLE lambda_pending_inputs_p_p0 PARTITION OF lambda_pending_inputs_p FOR VALUES IN (0);
CREATE TABLE lambda_pending_inputs_p_p1 PARTITION OF lambda_pending_inputs_p FOR VALUES IN (1);
CREATE TABLE lambda_pending_inputs_p_p2 PARTITION OF lambda_pending_inputs_p FOR VALUES IN (2);
CREATE TABLE lambda_pending_inputs_p_p3 PARTITION OF lambda_pending_inputs_p FOR VALUES IN (3);

CREATE INDEX i_lambda_pending_inputs_p_lambda_assignment ON lambda_pending_inputs_p (lambda_assignment_id);


CREATE TABLE lambda_assignment_vars
(
    lambda_assignment_id     int not null,
    generation          bigint not null default 0,
    variable_name       varchar(150) not null,
    update_date         timestamp(3) not null,
    original_size       int not null,
    value               bytea,
    large_value         bytea,
    PRIMARY KEY(lambda_assignment_id, generation, variable_name)
);


CREATE TABLE lambda_location_vars
(
    location_id         int not null,
    variable_name       varchar(150) not null,
    update_date         timestamp(3) not null,
    original_size       int,
    value               bytea,
    PRIMARY KEY(location_id, variable_name)
);


CREATE TABLE signing_keys
(
    key_id              int GENERATED BY DEFAULT AS IDENTITY,
    algorithm           varchar(30) not null,
    status              smallint not null,
    encrypted_key       bytea not null,
    public_key          bytea,
    created_at          timestamp NOT NULL,
    deactivation_date   timestamp,
    rotation_start_date timestamp,
    rotation_end_date   timestamp,
    PRIMARY KEY (key_id)
);



CREATE TABLE reports
(
    report_id           int not null,
    report_type         smallint not null,
    report_name         varchar(100) not null,
    display_name        varchar(150),
    description         varchar(250),
    sql_query           varchar(10000),
    dictionary_sql      varchar(1000),
    display_info        text,
    PRIMARY KEY (report_id)
);


CREATE TABLE report_params
(
    report_id           int not null,
    param_name          varchar(30) not null,
    param_index         smallint not null,
    is_required         boolean not null,
    data_type           smallint not null,
    display_name        varchar(60) not null,
    description         varchar(250),
    placeholder         varchar(100),
    PRIMARY KEY (report_id, param_name)
);


CREATE TABLE report_fields
(
    report_id           int not null,
    field_name          varchar(50) not null,
    field_index         smallint not null,
    column_name         varchar(30) not null,
    data_type           smallint not null,
    display_name        varchar(90) not null,
    description         varchar(150),
    PRIMARY KEY (report_id, field_name)
);


CREATE TABLE report_groups
(
    report_group_id     smallint not null,
    organizational_type smallint not null,
    name                varchar(250),
    description         varchar(250),
    PRIMARY KEY (report_group_id)
);


CREATE TABLE report_group_organizations
(
    organization_id     int not null,
    report_group_id     smallint not null,
    assigned_at         timestamp not null,
    PRIMARY KEY (organization_id, report_group_id)
);


CREATE TABLE report_execution_history
(
    report_id       int          not null,
    schedule_id     int,
    organization_id int,
    on_demand       boolean      not null default false,
    execution_date  timestamp    not null,
    execution_time  int          not null,
    row_count       int          not null,
    object_id       varchar(150),
    metadata        jsonb,
    error_message   varchar(250),
    output          bytea,
    schedule_date   timestamp,
    analytic_output varchar(150)
);

CREATE INDEX i_report_execution_history_object
    ON report_execution_history(object_id);

CREATE INDEX i_report_execution_history_schedule
    ON report_execution_history(execution_date, schedule_id);


CREATE TABLE report_metadata
(
    report_id   int         not null,
    name        varchar(50) not null,
    func_index  int         not null,
    field_index int         not null,
    description varchar(255),
    PRIMARY KEY (report_id, name)
);


CREATE TABLE report_group_reports
(
    report_id       int       not null,
    report_group_id smallint  not null,
    start_date      timestamp not null,
    PRIMARY KEY (report_id, report_group_id)
);


CREATE TABLE report_group_schedules
(
    schedule_id         int           GENERATED BY DEFAULT AS IDENTITY,
    report_id           int           not null,
    report_group_id     smallint      not null,
    parameters          jsonb         not null default '{}'::jsonb,
    timezone            varchar(50)   not null default 'UTC',
    execution_schedule  varchar(50)   not null,
    send_to             varchar(100),
    last_execution_date timestamp,
    next_execution_date timestamp,
    PRIMARY KEY (schedule_id),
    CONSTRAINT uk_report_group_schedules UNIQUE (report_id, report_group_id)
);


/*==============================================================*/
/* FOREIGN KEYS                                                 */
/*==============================================================*/

ALTER TABLE lambda_active_versions ADD CONSTRAINT fk_lambda_active_versions_master FOREIGN KEY (lambda_version_id)
    REFERENCES lambda_versions(lambda_version_id) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE lambda_errors ADD CONSTRAINT fk_lambda_errors_version FOREIGN KEY (lambda_version_id)
    REFERENCES lambda_versions(lambda_version_id) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE organizations ADD CONSTRAINT fk_organization_parent FOREIGN KEY (parent_id)
    REFERENCES organizations (organization_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE report_params ADD CONSTRAINT fk_report_paramets_report FOREIGN KEY (report_id)
    REFERENCES reports(report_id) ON DELETE CASCADE;

ALTER TABLE report_fields ADD CONSTRAINT fk_report_fields_report FOREIGN KEY (report_id)
    REFERENCES reports(report_id) ON DELETE CASCADE;

ALTER TABLE report_group_organizations ADD CONSTRAINT fk_report_group_organizations_organization FOREIGN KEY (organization_id)
    REFERENCES organizations(organization_id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE report_group_organizations ADD CONSTRAINT fk_report_group_organizations_group FOREIGN KEY (report_group_id)
    REFERENCES report_groups(report_group_id) ON DELETE RESTRICT;

ALTER TABLE report_metadata ADD CONSTRAINT fk_report_metadata_report FOREIGN KEY (report_id)
    REFERENCES reports(report_id) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE report_group_reports ADD CONSTRAINT fk_report_group_reports_report_id FOREIGN KEY (report_id)
    REFERENCES reports(report_id) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE report_group_reports ADD CONSTRAINT fk_report_group_reports_report_group_id FOREIGN KEY (report_group_id)
    REFERENCES report_groups(report_group_id) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE report_group_schedules ADD CONSTRAINT fk_report_group_schedules_report_group_reports
    FOREIGN KEY (report_id, report_group_id) REFERENCES report_group_reports(report_id, report_group_id)
    ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE organizations_hierarchy ADD CONSTRAINT fk_organizations_hierarchy_parent FOREIGN KEY (parent_organization_id)
    REFERENCES organizations (organization_id) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE organizations_hierarchy ADD CONSTRAINT fk_organizations_hierarchy_child FOREIGN KEY (child_organization_id)
    REFERENCES organizations (organization_id) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE dev_team_members ADD CONSTRAINT fk_lambda_developer_team_members_team FOREIGN KEY (dev_team_id)
    REFERENCES dev_teams(dev_team_id) ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE organizations ADD CONSTRAINT fk_organizations_admin_user
    FOREIGN KEY (admin_user_id) REFERENCES users (user_id)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
