# Vigilo Framework properties grouped by operational concern.

vf.aws.accessKeyId=?
#vf.aws.client.apiCallAttemptTimeout=
#vf.aws.client.retry.baseDelay=
#vf.aws.client.retry.baseThrottlingDelay=
#vf.aws.client.retry.maxAttempts=
#vf.aws.client.retry.maxDelay=
#vf.aws.client.retry.maxThrottlingDelay=
vf.aws.ecrPublic.catalogRefreshInterval=86400000
#vf.aws.httpClient.connectionTimeout=
#vf.aws.httpClient.maxConnections=
#vf.aws.httpClient.socketTimeout=
vf.aws.lambda.executionRole=?
#vf.aws.lambda.vpc.name=
#vf.aws.lambda.vpc.securityGroup=
vf.aws.lambda.vpc.subnets=?
vf.aws.region=us-east-1
#vf.aws.s3.client.connectionTimeout=
#vf.aws.s3.client.maxConnections=
#vf.aws.s3.client.maxTimeout=
vf.aws.s3.logsBucket=?
vf.aws.s3.sourceCodeBucket=?
vf.aws.s3.reportsBucket=?
vf.aws.secretAccessKey=?
vf.aws.sqs.resultQueueName=?
