# Vigilo Framework properties grouped by operational concern.

#vf.dataAccessMetric=
#vf.db.lambda_execution_stat.partShift=
#vf.db.lambda_execution_stat.partitions=
jdbc.maxActiveConnections=100
#jdbc.maxAge=
#jdbc.maxWait=
#jdbc.minEvictableIdleTime=
#jdbc.minIdle=
jdbc.password=?
#jdbc.removeAbandonedTimeout=
#jdbc.timeBetweenEvictionRuns=
jdbc.timeout=?socketTimeout=30
jdbc.url=?
jdbc.user=?
#jdbc.validationInterval=
