# Vigilo Framework properties grouped by operational concern.

#vf.lambda.applicationLogLevel=
#vf.lambda.assignmentLog.retentionDays=60d
#vf.lambda.async.key.exp=3600s
#vf.lambda.async.timeout=900s
vf.lambda.build.architecture=2
vf.lambda.build.command=?
#vf.lambda.build.deploymentTimeout=900s
vf.lambda.deleteLambdaAssignmentDataDelay=3600
#vf.lambda.dev.assignment.timeToRun=3600s
#vf.lambda.errorSilenceInterval=24h
#vf.lambda.errorSnsTopic=
#vf.lambda.errorTextMaxSize=
#vf.lambda.expiry.gracePeriod=30s
#vf.lambda.idleVariables.maxCount=
#vf.lambda.idleVariables.maxDays=
#vf.lambda.loc.requests.maxBatchSize=
#vf.lambda.maxExecutionTime=
#vf.lambda.maxInputDataSize=
#vf.lambda.maxPendingRuns=
#vf.lambda.maxStatsSize=
#vf.lambda.maxTimeoutsPerHour=
#vf.lambda.memory=
#vf.lambda.ml.key.exp=
#vf.lambda.ml.memory=
#vf.lambda.ml.timeout=
#vf.lambda.org.requests.maxBatchSize=
#vf.lambda.retries.delay=3s
#vf.lambda.retries.max=
#vf.lambda.retries.maxPendingRuns=
#vf.lambda.schedule.triggeringInterval=1s
#vf.lambda.sqs.timeout=200s
#vf.lambda.statTimeout=15s
#vf.lambda.storeErrorText=
#vf.lambda.systemLogLevel=
#vf.lambda.timeout=600s
#vf.lambda.timeout.start=10s
#vf.lambda.uploadErrorSnsTopic=
#vf.lambda.user.key.exp=600s
