# Vigilo Framework properties grouped by operational concern.

#vf.artemis.maxSize=
vf.artemis.password=?
vf.artemis.url=?
vf.artemis.user=?
#vf.artemis.warnSize=
#vf.kafka.maxSize=
vf.kafka.servers=?
#vf.kafka.warnSize=
#vf.mq.maxTimeDifference=
#vf.sqs.maxSize=
#vf.sqs.messageRetentionSeconds=
#vf.sqs.visibilityTimeoutSeconds=
#vf.sqs.waitTimeSeconds=
#vf.sqs.warnSize=
