# Vigilo Framework properties grouped by operational concern.

#vf.account.user.key.expiry=30d
#vf.encryption.initKeys=
#vf.encryption.key.inactiveTime=
#vf.encryption.key.update_interval=
#vf.password.format=
