# Vigilo Framework properties grouped by operational concern.

#vf.lambda.asyncResponse.maxRecords=
#vf.lambda.asyncResponse.pollInterval=
#dsp.analytic.lambda.rejectedDelay=
#dsp.analytic.lambda.rejectedLog=
#dsp.analytic.lambda.rejectedRepeat=
#dsp.analytic.lambda.requestThreads=
#dsp.lambdaAssignmentLog.logInterval=
#dsp.lambdaAssignmentLog.maxEvents=
#dsp.lambdaAssignmentLog.maxPoll=
#dsp.lambdaAssignmentLog.pollInterval=
#dsp.lambdaCode.pollInterval=
